# Generated by Django 5.2.6 on 2026-06-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expected_return',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='return_value',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='income',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='investment',
            name='inv_type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Gold', 'Gold'), ('Mutual Funds', 'Mutual Funds'), ('FD', 'FD'), ('RD', 'RD'), ('Real Estate', 'Real Estate'), ('Crypto', 'Crypto'), ('Other', 'Other')], default='Stock', max_length=50),
        ),
        migrations.AddField(
            model_name='investment',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='investment',
            name='return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.profile'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='expenses.profile'),
        ),
    ]
